[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "85448cda87cefb788b803c585e947ffd3481db0f"
libgfortran_version = "5.0.0"
os = "macos"

    [[Dierckx.download]]
    sha256 = "2487401012185559cba8673798b87c20b8aee5db215a41a3117bfc8348223046"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "3aa05ca32bc7d7bac659788f3eaca7042e9c9ec0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "c441c38f691171b3f7bcc0c936535478c8c8342c41db669d4a8da0d269dbbe7d"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "b85d216b93196ce36b4ef118cc952d44c6baf974"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "58e3d541830e3baac022ec42b56b013d0a618039a722e27d8fc04bebd6cae03d"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "623adc28e3260dda5b7b842d3ec9ec242ff34c81"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "5e67bd86acea7259b286827e6964e9c0564467933169dd0a182453f1d68f0dbe"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "ceb39285c5453a391a7733bee926c0bb40e9be50"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "7488c96f951189b40309ed01e2165940918945d99cf05b69d19db5e73a9a7936"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "b2ff8a67e8856ae25409a4f1099b16e4f165a6b5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "1fae0d42bc676a0b23c164b6d5f954249200b71de001fdcbf43b34f0dd186ca7"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "361ba195708f9a8b1d3586d5697563f44d6f4f9d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "88f2ec3da95c568d35e09d66bdcb1bf6ced90972b9bbf0aa46b7d8bfa4e29cb1"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "b2e3629867b4557de75af0d7e18ddc26af0b2735"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "1743f558f77cdc928f543243a717b63ee0555071b94c32dadccfc2a7e389f50f"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "6ea12bb6ae438cb7bbe038954cdada2b52e1ed2d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "cd6a0e429907143bc0612cab8de12af80c4e7156b83127942d562e79be4faf1a"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "426e256b68e7be3ad659c35f7c5edcf3f90b30d3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "0c9ffa423511fbbb6ce8f80064c79cd242d4de7175d8f05dfb28c900c41b4d24"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "67cbcdb2df033fb75ba1ea404d9c896ba57f0d2d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "f635ebb04b1a5c1862d6fc2c9d5b64b8ea349927387019b3f343255d72822550"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a4f917777788abe9fa957345379ffbbc33500e29"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "8c904f6c94658952f9c62efbefb032f3290bd63567cc1d6df099412daca963db"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "be5cc6545ec9223a1662057b81bf0a65ec740763"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "4f9df7abe748c54e71975f610c260959a4414cd3bf0012ae498be7fbdf8c279b"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1fb4fec7841187b56a11243aa92a660c6bb7baaf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "94cfb8729766f4d1244fc1f449a8f72f07cd2bcd1a9207e124a34bb2061142bc"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fab8c9caf80de20753d66acaccf16d757d25d6c9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "9f13211d058e5bfbb43600e58c2ebf7d43f613ed9a06048acad18494769ec7ca"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4d366467304fe571f5ffc506fbda1b4ff3ebc30"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "ad29c4cc6029d7e0257e3e5b942e77771d717027fd1733eacec16364181c35a5"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2254de0ae00e3f64504e96eb5ae27a1d542133e0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "187319434d3004cabd61fb1401c5e183450e5b01938b0270435fc43871184c5f"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab96fe87410bc2a39f8f070f96e840f118712d91"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "a2399ec2d50281c76940d4d99e4710cc039ccec90ab7f50053560c7ab8acc96f"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d87e978731e2b7dfe270995434b27dd0f6ef8a1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "9ae4de811295200db61d5c9dd03056290de8198fc5b15a5720b272acc1d76bc7"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd9edf57497f38108185716b67c6de8a49e89d53"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "156538eaa6e23d58078f17ad974473700137ef1dccce4c5da68844371b1a7825"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "65eae9796d773e43c49512e6306c62494654d6fd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "7b5d0cc7ce9ee632e39047a55c8d613b1f7065aaf0498751624b4efa5886f6f7"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "494b6175228bf40d677d06255e27fd4aff4a5bb6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "a98e1217ad0ec99c2afdf4398f51d43b5a0c385ee8feec7adcf18cadff05f28b"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-linux-gnu-libgfortran3.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "a77ade1f328612823c536fd964790517bcbca253"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "4a76df22837be840220e78ae6f49c4dc70e26d4e890bf304a654d3e5876696bd"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-linux-gnu-libgfortran4.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "a1b4c7aa48ba4002cc42924a4ef3408f2fba874b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "60ff62091c5fdd14a61feec55adfc89d9db615e32a180b12872484647a9abf0f"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "48df31ac7cb335cc42794a04b4f87fb6d0e3a64b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "87fbeca12a2e352524612bd624d420660d2cae0f30fb05e20d9ad710aadeea71"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-linux-musl-libgfortran3.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "d9004cef31e002a9989d91a09d969b57b2a054a1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "513c0b7c576a549cb1cdb78b1980fc9ae8882c1fcc9d0271742b46bcd1f690f5"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-linux-musl-libgfortran4.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "504a45562db32861a4ec73703bc89fb3feddd95e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "d2035f344a9b498fba58a589bef8a060486bdebc7c306f2a036471a1807cbfe4"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-linux-musl-libgfortran5.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "a2e6fe1898206db2251b0c4ae2373f91463a38fb"
libgfortran_version = "3.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "295d424fc088a3a4b7ad7a00e25c0ac583602113e6828b01f223ddc1bcf1b4ba"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "4d189cae35896eccdfe3ccc4d8aeecbe66219968"
libgfortran_version = "4.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "3198d0a1e6d89f7808d3d693618ea55998d1bfdf08ed6e2d7d3dc2dc22c5c9eb"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "52b2c8758a3a9fc9ad3441dda9d758cdfb50d9fd"
libgfortran_version = "5.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "f27ba0ad43cb6a752e18cc230456faeccfc35226e024adc5a2be06d5b7c02d0b"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[Dierckx]]
arch = "powerpc64le"
git-tree-sha1 = "950102f8d55c05ad128d68aea26baeec7a7f2286"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "26b749cbdbea608a9cc25e3ecc28d67cdd3b17e05a682aa97cde01255cca9a66"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Dierckx]]
arch = "powerpc64le"
git-tree-sha1 = "95675384520449e4664f69dd5ca1a9fc603de008"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "9d96932bfb142059c67dd96d543071008f5f6d5f9161775ca2be1b088e20caae"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Dierckx]]
arch = "powerpc64le"
git-tree-sha1 = "2bba8f4e3df47c1772f627912a76f5c19da9eacc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "b45e826b318fe4e5a84714918f76863d48d381781f255a453c9f865c035b2609"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "riscv64"
git-tree-sha1 = "480359d5ff1b5b4fd15179d95f9cdf5b8ed62321"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "b072f4c7a71f2e1eee75c84747a4d726789bcecd83f873f69d9a6fd80fd13be4"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.riscv64-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "ed99b5587d4c25e17cb25ac07f35f581e88bdd61"
libgfortran_version = "3.0.0"
os = "macos"

    [[Dierckx.download]]
    sha256 = "8773878a6bb32947e9f0814965ffb1e7bfbca739499a083a3fcfa46378aa3805"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "5cc126e0f23a03ed6dbd9430f4d262a7c4fe3af2"
libgfortran_version = "4.0.0"
os = "macos"

    [[Dierckx.download]]
    sha256 = "8ef30e3eaf02e2f7161f9d9fe2234199d2083b437ad968eb8bbc077497ba77b0"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "488405560abaa437aad29e964b87673babbc36ca"
libgfortran_version = "5.0.0"
os = "macos"

    [[Dierckx.download]]
    sha256 = "881c8e057e94a99cd6b1b250a011648ec0832297d15ed8ede6ba1526b84eabe1"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "497532aa5d187affd61d08fe333f3d5150efa68c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "811d260a0b994a2d74ff1fb61c0be7a81cff4d3dad4d6fe1ae122403afcaed35"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "4f9f1c52f5fa51535d66484b616f3463de26366b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "ce8a1595efd20cbc14dd09dda288d41247db823a8d72b0e07a4a1dfa52a3d980"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "ca4d5ef23f014b64371d44c4e1c0ead00f0b13f1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "63090f404fc28e9e304d5a7effb17187404bf691286f464e94529597f10386b2"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "d9fc44be9b8a4ff508c736e79ce79be6331a4f95"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "8a3c217e87e82eecb3e0120af45bb9ede194ea9e451c867a20a9e1b3e42c4eec"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "d97c81529432b44ef00de0b90e958dce29112bc2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "b95b1bbbaf8b354e9d0b4d563b38746eac949b58d63f7f85e8f7648b8ffe3fe8"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "3207778df5fb1c9fd59c577bae6ee60e303cbeb7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "c9e1d408e9093816e568c8d374a5071daadb013e56cd6e21f4ff4101b398715d"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "d4572a76151e642e408551c4fa78c3fdde4407b5"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "c2ab18fdcaf0f9432bc36aa905d8ba28f2400bef2c9f38796e3a507c32b95940"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "57449aeec1caa4300f7ed5654b92b8b44fc59910"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "7ccfd8cc7c8572f85d5b8b102b7e6eb5ccb1bbe4b44887e8cec132e7f4d65b4e"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "c42f2c206079660cd9a17f54c4ceb528a7eed825"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "cc2805ce9e7d41b3dff0b6c325f3fc7251f757b754cb832e441c70345d5b5ad7"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "cdae7b3cb08314aae5313b6240bf40f5871d74fd"
libgfortran_version = "3.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "6b845350ccec5187f2b28ad5c138f14a1148911e3dba202646750c1db32d76d1"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "0089feb2f82df2ea2497a542ea705d33b5b40625"
libgfortran_version = "4.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "204820a764a8d597bc8f88f6bfaa03f7df408591c0e917fd43b1cd114349cf65"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "e57a829fb65c41446638a9f9ab6e0cb20cc31b71"
libgfortran_version = "5.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "c61a33bd087c3f92a8d8b8e376f63a95ad6a8c92bc3db082e479ed0f66a1109a"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.1.2+0/Dierckx.v0.1.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
