[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "8089f3ae963cf224afb7893165ee689eabc36b16"
libgfortran_version = "5.0.0"
os = "macos"

    [[Dierckx.download]]
    sha256 = "817b18bf37a2bc00eb6e3b78dcaa00e3f8543df37b2c942ae144b8da8b6069f5"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "56b9f4e9eb5b75a2f68415439dcc93d2f6969228"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "534a14d1fd92f448e7358a4d7bf8bdc6fe0347589867509b3337fd68715f9ab9"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "48162c1932352146df85b6aa007a896d07430ac9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "133872d81215936ed7bed530671c72dfe024a8896b0d832738aaaa27dc7ca209"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "48c35e3d4cf1eb1d056af3f66fb295b182669dff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "e19a22b78d12729d4cc7ad04d73536a3c13f51e5f747b24a9b1ea0ba8ac25430"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "7127455b13cde40c82ae023e13856d068083a405"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "0e6650b643c85db00d951e7fc57e444dc35f1d55a2ebc874e4d3ac1c54b5b471"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "07285f618e646cea87e1128e75bc736adfe681ac"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "e5089f2b598881f2717e5cf01dec49342b66523c0800cce5acda36f637834e5b"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "1509fa1a358deb90f44e11be6e591755d41d6917"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "612381d036822a02a870dbbfd9badcc3a63d0f793c0acc172050c3e3e73511fb"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "d3f035bc564d26254c3a16fdf77e28a443a7f4fa"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "b3388fe659949a11de4aa0d565d8e47a35e6de0ada7f6fc0854774386a99b2c8"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[Dierckx]]
arch = "aarch64"
git-tree-sha1 = "369b8c3b4611e62855ecc4d1d9a7a279d90670d7"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "0e9f48eb1f24662bce7b72e9744366403aaefa114d028ae41baf648158e70fc4"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dec74c5e36ff5bfcb19ae36a7ca613c73bd5dad6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "2afc446381d6e64ed8b6b39dd351058ee7e224c206071252e2c779ca555c5ac9"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ddf8a9e1eb0dd45d8f83a1e4b8146761708b8aea"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "c412bb8390c70abbe41e7c211d25965825fd5f5e421a335144ef4c925a8157ae"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3464f2169f1ca8987a6b267f4bcd2aa300d31153"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "06e5e59c9380074cdf4f12bfeffc33aa690acd9f77706c2f4bb1d2067eb3dbfc"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a9497046c903166fa25e19722c7e47c3e3403253"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "44e19a88c7aa41e497a4a12e86d285609f7fefb356e23e846d52804681eef017"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9be35486bfb2e982a76a042a8828b09e72ed4a10"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "33747c0ad1176999d5557516cdb3dadfa8b4c1ad3a054b246c9df5e5472c8332"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Dierckx]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f40018eb56fb4c98885dfcf5c99b42ff7f38e043"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "1d8ce1d4bd30ab7b63480ca850a53bc56426be7a9ce230f6cdf365f8e89854c4"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5436d704428110d7341085812b10f242be829594"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "0e914332aa5237359212ca37d6a83cfa2e2d799dc228adaa7d70c28f1fc0846d"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "73afc76cefc29fb9122199f1bf34183a310e4bf8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "4a3ad3522c9fd9d901edf95e6cb079826c90f0940d32a4e7c5c0a3f798fbea8d"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32668863115b4e2c2d1db8369c86bd679ecff3bf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "a75237a0d059aeaaa328066bacd48e3f6999eaac9eb979788dc045427dd362b7"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6cde30e713e15c9f4fdffb7db68ba8a7a7260481"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "10ab4fc58eb18dd41677effd213219176c3460031ca47462f413b4fc54528813"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "302c829084bd57621e9f306e561d79140f44a51a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "2fc85b402319e2184b61ce82e082d3c263bab1069e595e49debf77fbc302b607"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Dierckx]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "859415bcd8e6e135f00c5f3135c584272f8d0ee1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "c32dc19edc70f7dbfc0968cde1576f8e199bc1f0690ddbc9e92fa77868bbe2c3"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "c9a97646fef96ff1cd3440047b88daf0e8cde83b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "5dd0cef11815a1962f677a0f9508b4a6fb81c6f233a91a1bbc7fb8dbeae39569"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "a64b3fc8e9b87fee25ee11e867bca3f2553e2a7e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "076f29a11d70d66181579e98d254b3918bd734e2cb39a5195c2c9dbe096df84b"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "65c2e37ca852fa8e9b82e0e315d349a1321125e5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "de69d88c709f7389f9d738a66a546aa4caef65b0c51e5a0698afd7baab5fd405"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "178163101bda73dce6f7561225b60ebf7353296f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "e078d5ec21faefafefb5b8bf86292366981796f66f9aa34238ff39074b700321"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-linux-musl-libgfortran3.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "66ad003cfb6e259b7e50578aca5bdf70eef96f57"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "81dfcd66243fef81410bc19087851a67152ef51f963d07102061fd2361f4b595"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-linux-musl-libgfortran4.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "04a7edd7cbcca1878b4ef37532ab4327355ac171"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "cbc2d2feee861cc31744e2eaf25aca16fdccca56a7649682f1d9b77e85219b29"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-linux-musl-libgfortran5.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "e93531a3c588d034db1583fa4c4114e07829d992"
libgfortran_version = "3.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "f3f0284f5b59cf31c9b25ee7d8962e128d5449114cc56cb9cb437a6cd89c0860"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "60097ff5f605615499b6728b0d459df71a2a4ccc"
libgfortran_version = "4.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "df3d0f48133e626cd91addc56c0c9fabfdbe609810dd3c28944ba8f180a21cea"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Dierckx]]
arch = "i686"
git-tree-sha1 = "2c5cc942bfe61fdc7103e86daeb23e480bed21c9"
libgfortran_version = "5.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "cda7c143d2866eade32ce5d0d942fc43b999b83c7c69cd789d14571ee109303f"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Dierckx]]
arch = "powerpc64le"
git-tree-sha1 = "abc21d7bbf1e5ef058528b5a4d1b25543cdb04ec"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "288384318660f44ae58697b40ca75a924e0a574862af324e2665119c0df6412f"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Dierckx]]
arch = "powerpc64le"
git-tree-sha1 = "631a7cf9e7834234f3ce24271383dcf0d0f74a2b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "3faabb97b52913fd869b6bbdaec8af15780c8d11ed23a83bfd301229b13ee644"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Dierckx]]
arch = "powerpc64le"
git-tree-sha1 = "7d5e475fa4fd15b24d263a1f4b7d97eb751077e8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "1cf57260b5157f1522c8c873627ab339ef82c2dc01ac1b03d00e00eb704cd712"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "riscv64"
git-tree-sha1 = "556c1fb57e283495d62290544f760532a3924ef4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "2b5c7ed8a9c65a2723a60f7fd4c40f26317d90872dc5d608cb05e4b7f0666d89"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.riscv64-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "1193ec0be8725349b5002402492efd20db50b298"
libgfortran_version = "3.0.0"
os = "macos"

    [[Dierckx.download]]
    sha256 = "4584d87812355dedad97fc8fcecda0243ec4d0b579f6aef78701429419c8befa"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "c8b1ce2fd91d195f940d36ce22dd409b1d32895b"
libgfortran_version = "4.0.0"
os = "macos"

    [[Dierckx.download]]
    sha256 = "7acbc834c8f7e38fda830015fc13be7880e74c39d37db7bba8da350f1343a69a"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "bdd432b2c6ec6f0a9d9b2ee708c1c707854076fd"
libgfortran_version = "5.0.0"
os = "macos"

    [[Dierckx.download]]
    sha256 = "b20886d6bc379bbbc14292362e9258797fcb3198210eac5e9489a0fd06814068"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "47d101ee624e059ccdb716fa7492686e5e34a5aa"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "45b5073eda39f184d3888c4c15a014c2cabe4db974875cdb1c152eb3b4457d17"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "d6a700aa5e79ba9dfec8bd033d1a3de926219bd9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "1149f200cc73826ea1d5182453349dc2338e6bddf01b9b5eb577b53ac9c415a3"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "84929b756ffb0c74c96cd2779caa935fa733436c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "d4ddbb711b4d0a7cd71ca017c11c9f9205a737c31ebf117d161d44090642067f"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "dfd0722088df519d09ee5eaa8998b2278bcb7888"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "0e619cdef5e7fb91b2265b50b4bbb70c8457f031f4fa57cb084d695598363c82"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "b3d214941061039fea417e9fe2d7256391c9ec0a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "d7e93d20357ceaaf856ed0358b4cc938e4dcf52d009de7d437c5973044a408df"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "f425fe439c79528e4ad12c128fad5f7085f9dedb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Dierckx.download]]
    sha256 = "019eecfee8964a52b1d3a20aaed9e9f17b869826211ec1a53f3a2510cb624e78"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "38aee367214b487b1d37e6d2a1fead3eb7d86e46"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "34e629f57084d21448d544b03c61153fd88bc2c1186f6352335f9588fbaea83f"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "1053388d25dda96ff256b63d6ea6f8a1d7a3d8a6"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "4d272684a7e7afd295410c31d08ae8d78ef3f85c9dc44a262f09facb7bc50a78"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "93b986cc19231dc0651854812cbafe54c0a45dc2"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Dierckx.download]]
    sha256 = "eec66e03bda428f949d9c4cf0e5c364768f1fef22254876338faf71824caf217"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "a250ebe1a7300af96dbcde7d30c9dc0a8b11855e"
libgfortran_version = "3.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "f83876dabf9c77d8c95270e9a47f223563cd6d1f1b75258dc9cc0ae4d7678269"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "211718ef79449067ecd316c463c13f42f3eddf6c"
libgfortran_version = "4.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "93842d6a93b2e012dad7d27a2fdecfb95916881f3ab463ba176eb9c4c70c2db3"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Dierckx]]
arch = "x86_64"
git-tree-sha1 = "64edfe63872fd7750e7403a6f22608f4b94121a7"
libgfortran_version = "5.0.0"
os = "windows"

    [[Dierckx.download]]
    sha256 = "4b392005ffea272fa39c79dd0287d368b33d0df250f7347697021bd51d82801d"
    url = "https://github.com/JuliaBinaryWrappers/Dierckx_jll.jl/releases/download/Dierckx-v0.2.0+0/Dierckx.v0.2.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
