# Autogenerated wrapper script for Dierckx_jll for aarch64-apple-darwin-libgfortran5
export libddierckx

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Dierckx")
JLLWrappers.@declare_library_product(libddierckx, "@rpath/libddierckx.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libddierckx,
        "lib/libddierckx.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
